### ISSUE TITLE
1.16.1 Not Working

### ISSUE THREAD

**Issue by gloamingwildwoods** [SaitDev/MobArenaExtension#11]
Tried using this with 1.16.1 with just a basic single wave spawning in a mythicmob, and resulted in a failed to parse monster error. I've tried reloading plugin, restarting server to no avail.

**Comment by MaksyKun** [comment]
Same here. Our server is running on 1.16.4/5 - With the following message:



[17:45:43 ERROR]: Error occurred while enabling MobArenaExtension v0.1-SNAPSHOT (Is it up to date?)
java.lang.ClassCastException: class com.garbagemule.MobArena.MobArena cannot be cast to class com.garbagemule.MobArena.MobArena (com.garbagemule.MobArena.MobArena is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @28802db8; com.garbagemule.MobArena.MobArena is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @555e349a)
        at me.sait.mobarena.extension.MobArenaExtension.initMobArena(MobArenaExtension.java:104) ~[?:?]
        at me.sait.mobarena.extension.MobArenaExtension.onEnable(MobArenaExtension.java:42) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Purpur-1118]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364) ~[patched_1.16.5.jar:git-Purpur-1118]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Purpur-1118]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366) ~[?:?]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:318) ~[?:?]
        at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:380) ~[?:?]
        at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) ~[?:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Purpur-1118]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.16.5.jar:git-Purpur-1118]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:813) ~[patched_1.16.5.jar:git-Purpur-1118]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:775) ~[patched_1.16.5.jar:git-Purpur-1118]
        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:468) ~[patched_1.16.5.jar:git-Purpur-1118]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:435) ~[patched_1.16.5.jar:git-Purpur-1118]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1413) ~[patched_1.16.5.jar:git-Purpur-1118]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[patched_1.16.5.jar:git-Purpur-1118]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Purpur-1118]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[17:45:43 INFO]: [MobArenaExtension] Disabling MobArenaExtension v0.1-SNAPSHOT

**Comment by MayhemBill** [comment]
same issue on 1.16.5

**Comment by MayhemBill** [comment]
```
01.06 19:57:22 [Server] INFO Enabling MobArenaExtension v0.1-SNAPSHOT*
01.06 19:57:22 [Server] ERROR Error occurred while enabling MobArenaExtension v0.1-SNAPSHOT (Is it up to date?)
01.06 19:57:22 [Server] INFO java.lang.ClassCastException: class com.garbagemule.MobArena.MobArena cannot be cast to class com.garbagemule.MobArena.MobArena (com.garbagemule.MobArena.MobArena is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @63ed0d5b; com.garbagemule.MobArena.MobArena is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @6ae30a8b)
01.06 19:57:22 [Server] INFO at me.sait.mobarena.extension.MobArenaExtension.initMobArena(MobArenaExtension.java:104) ~[?:?]
01.06 19:57:22 [Server] INFO at me.sait.mobarena.extension.MobArenaExtension.onEnable(MobArenaExtension.java:42) ~[?:?]
01.06 19:57:22 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-756]
01.06 19:57:22 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-756]
01.06 19:57:22 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-756]
01.06 19:57:22 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-756]
01.06 19:57:22 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-756]
01.06 19:57:22 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594) ~[patched_1.16.5.jar:git-Paper-756]
01.06 19:57:22 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-756]
01.06 19:57:22 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-756]
01.06 19:57:22 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-756]
01.06 19:57:22 [Server] INFO at java.lang.Thread.run(Thread.java:829) [?:?]
01.06 19:57:22 [Server] INFO Disabling MobArenaExtension v0.1-SNAPSHOT
```

**Comment by 674049050** [comment]
So do I encounter this problem

**Comment by SaitDev** [comment]
latest version drop support for MC 1.16. pls update to mobarena 0.107 and MC 1.18
