### ISSUE TITLE
NullPointerException: null

### ISSUE THREAD

**Issue by mibby** [SaitDev/MobArenaExtension#4]
MobArenaExtension dev 20
PlaceholderAPI dev 58

Downgrading to dev 19, all is fine.
```
[22:01:37] [Server thread/INFO]: [MobArenaExtension] Enabling MobArenaExtension v0.1-SNAPSHOT*
[22:01:37] [Server thread/ERROR]: Error occurred while enabling MobArenaExtension v0.1-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: null
	at me.sait.mobarena.extension.MobArenaExtension.initPlaceholderAPI(MobArenaExtension.java:143) ~[?:?]
	at me.sait.mobarena.extension.MobArenaExtension.onEnable(MobArenaExtension.java:40) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-509]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) ~[patched_1.13.2.jar:git-Paper-509]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-509]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-509]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-509]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[22:01:37] [Server thread/INFO]: [MobArenaExtension] Disabling MobArenaExtension v0.1-SNAPSHOT
```

**Comment by SaitDev** [comment]
Reopen if you still have this problem on build 21 onward
