### ISSUE TITLE
Failed to load due to PAPI

### ISSUE THREAD

**Issue by SXRWahrheit** [SaitDev/MobArenaExtension#9]
```
[11:09:52] [Server thread/INFO]: [MobArenaExtension] Enabling MobArenaExtension v0.1-SNAPSHOT*
[11:09:52] [Server thread/ERROR]: Error occurred while enabling MobArenaExtension v0.1-SNAPSHOT (Is it up to date?)
java.lang.NoSuchMethodError: me.clip.placeholderapi.PlaceholderAPI.registerPlaceholderHook(Ljava/lang/String;Lme/clip/placeholderapi/PlaceholderHook;)Z
	at me.sait.mobarena.extension.integration.placeholderapi.PlaceholderAPISupport.register(PlaceholderAPISupport.java:141) ~[?:?]
	at me.sait.mobarena.extension.integration.placeholderapi.PlaceholderAPISupport.onEnable(PlaceholderAPISupport.java:32) ~[?:?]
	at me.sait.mobarena.extension.MobArenaExtension.initPlaceholderAPI(MobArenaExtension.java:146) ~[?:?]
	at me.sait.mobarena.extension.MobArenaExtension.onEnable(MobArenaExtension.java:44) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-134]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-134]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-134]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-134]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:941) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-134]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[11:09:52] [Server thread/INFO]: [MobArenaExtension] Disabling MobArenaExtension v0.1-SNAPSHOT
```

MaEx b37
[Mon, 10. Aug 2020 11:13:12 CDT INFO] MobArena version 0.104.3-SNAPSHOT
[Mon, 10. Aug 2020 11:13:09 CDT INFO] This server is running Paper version git-Paper-134 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Comment by SaitDev** [comment]
Closed by #10
